using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using iotms.Permissions;
using iotms.Devices;

namespace iotms.Devices
{
    public class DevicesAppService : DevicesAppServiceBase, IDevicesAppService
    {
        //<suite-custom-code-autogenerated>
        public DevicesAppService(IDeviceRepository deviceRepository, DeviceManager deviceManager)
            : base(deviceRepository, deviceManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}